version: '3.8'
services:
  website:
    build:
      context: .
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/usr/share/nginx/html # Bind-mount the current directory to the container